[project]
name = "karp-api-client"
version = "0.1.4"
description = "Client for accessing Karp API."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Språkbanken", email = "sb-info@svenska.gu.se" },
]
dependencies = ["attrs>=24.3.0", "httpx>=0.28.1", "returns>=0.23.0"]

[project.scripts]
karp-client = "karp_api_client.cli:app"

[project.optional-dependencies]
cli = [
  "json-arrays>=0.15.0",
  "typer>=0.15.1",
]

[dependency-groups]
dev = [
  "anyio>=4.8.0",
  "pytest>=8.3.4",
  "pytest-asyncio>=0.25.2",
  "pytest-coverage>=0.0",
  "ruff>=0.16.2",
  "syrupy>=4.8.1",
  "ty>=0.0.81",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
