[project]
name = "karp-api-client"
version = "0.1.4"
description = "Client for accessing Karp API."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Språkbanken", email = "sb-info@svenska.gu.se" },
]
dependencies = ["attrs>=24.3.0", "httpx2>=2.13.0", "returns>=0.23.0", "typing_extensions>=4.12.2; python_full_version < '3.11'"]

[project.scripts]
karp-client = "karp_api_client.cli.app:app"

[project.optional-dependencies]
cli = [
  "json-arrays>=0.15.0",
  "typer>=0.15.1",
]

[dependency-groups]
dev = [
  "anyio>=4.8.0",
  "pytest>=8.3.4",
  "pytest-asyncio>=0.25.2",
  "pytest-coverage>=0.0",
  "ruff>=0.16.2",
  "syrupy>=4.8.1",
  "ty>=0.0.81",
]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "P7D"
